### ISSUE TITLE
Will this only works if the victim account is also using VPC endpoint to access thier resources?

### ISSUE THREAD

**Issue by eclipse0xe** [Frichetten/SneakyEndpoints#2]
Take S3 as an example, if I want to exfiltrate or explore the data stored in S3, the victim should have configured S3 to be accessible via VPC endpoint, in that case, you are successful to hide the traces but can do any operation if the victim account has not set up VPC endpoint. 

Please correct me if I',m wrong.

**Comment by Frichetten** [comment]
:wave: Hey there. By default this method should work out of the box for any API service supported by SSM. Specific to S3, the victim does not need to configure or use VPC endpoints for you to use this method.
